version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - tech-db:/var/lib/postgresql/data

  back:
    build:
      context: ./back
    ports:
      - 8081:8081
    depends_on:
      - postgres-db
    environment:
      - JAR_FILE=${JAR_FILE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres-db

  front:
    build:
      context: ./front
    ports:
      - 9000:8080
    depends_on:
      - back
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL}

volumes:
  tech-db:


networks:
  default:
    name: tech-app
