java:
  version: 17

user:
  name: "Andres Brito"
  email: "robin_brito@hotmail.com"

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/tech_fellow_test
    username: brito
    password: ${DB_PASSWORD}

  cloud:
    gcp:
      bigquery:
        credentials:
          location: file:./bigquery-key.json
        project-id: techplus stage2
        dataset-name: bigquery-public-data

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

appDescription: "Tech+ FellowShip Test"
appVersion: "1.0.0"