java:
  version: 17

appDescription: "Tech+ FellowShip Test"

appVersion: "1.0.0"

user:
  name: "Andres Brito"
  email: "robin_brito@hotmail.com"

spring:
  profiles:
    active: dev

  cloud:
    gcp:
      bigquery:
        credentials:
          location: file:./bigquery-key.json
        project-id: techplus stage2
        dataset-name: bigquery-public-data

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

